sudo: required
#  Manually install python on osx

matrix:
    include:
        - os: linux
          language: python
          python: 2.7
          env: TOXENV=py27
        - os: linux
          language: python
          python: 3.3
          env: TOXENV=py33          
        - os: linux
          language: python
          python: 3.4
          env: TOXENV=py34
        - os: linux
          language: python
          python: 3.5
          env: TOXENV=py35
        - os: osx
          osx_image: xcode6.4
          language: generic
          python: 2.7
          env: TOXENV=py27
          env: PYTHON=2.7.12
        - os: osx
          osx_image: xcode6.4
          language: generic
          python: 3.3
          env: TOXENV=py33
          env: PYTHON=3.3.6
        - os: osx
          osx_image: xcode6.4
          language: generic
          python: 3.4
          env: TOXENV=py34
          env: PYTHON=3.4.5
        - os: osx
          osx_image: xcode6.4
          language: generic
          python: 3.5
          env: TOXENV=py35
          env: PYTHON=3.5.2
before_install: 
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update;
    brew install mono;
    brew install pyenv;
    pyenv install $PYTHON;
    pyenv local $PYTHON;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe";
    sudo apt-get install software-properties-common;
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
    echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.2.4.4 main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list;
    echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list;
    sudo apt-get update;
    sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install mono-devel mono-complete referenceassemblies-pcl ca-certificates-mono nunit-console;
    fi
install:
  #- ./.travis/install.sh
  - pip install tox
  - pip install tox-travis
  - pip install six
  - pip install pycparser
  - tox
  - python setup.py build_ext --inplace
script: 
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - python src/tests/runtests.py
